###
GET http://localhost:3000/debug-sentry

###
POST http://localhost:3000/as
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30
}
 
###
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json
   
{
    "name":"Purno",
    "email":"imasyhur68@gmail.com",
    "password":"Purno123",
    "password_confirmation":"Purno123"
}  
  

###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json
 
{
    "email":"imasyhur68@gmail.com",
    "password":"Akuadalah123"
}


### 
GET http://localhost:3000/api/v1/auth/whoami
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTcwMDM2NDUwMX0.lvVj2ecRX93lWNn4jkEGt1qhWZGO2gDxsA_NJYzyxr0

###
GET http://localhost:3000/api/v1/auth/forgot-password
Content-Type: application/json

{
  "email": "imasyhur68@gmail.com"
}

###
POST http://localhost:3000/api/v1/auth/reset-password
Content-Type: application/json

{
  "password": "Akuadalah123",
  "password_confirmation": "Akuadalah123"
}

POST http://localhost:3000/notification
Content-Type: application/json

{
    "user_id":1,
    "title":"New message 2",
    "body":"pesan baru kedua"
}