###
GET http://localhost:3000/debug-sentry

###
POST http://localhost:3000/as
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30
}
 
###
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json
   
{
    "name":"Purno",
    "email":"imasyhur68@gmail.com",
    "password":"Purno123",
    "password_confirmation":"Purno123"
}  
  

###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json
 
{
    "email":"imasyhur68@gmail.com",
    "password":"Purno123"
}


###
GET http://localhost:3000/api/v1/auth/whoami
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTcwMDMyOTkwMn0.PdgEwak3sv2cmvGRS57paOJApgU7m3s8CMhHIHY1K4w
